### ISSUE TITLE
cordova-sqlite-ext and ionic

### ISSUE THREAD

**Issue by ghost** [brodybits/ask-me-anything#22]
using ionic 5 & capacitor on iOS, I cannot work out how to open a database that is being copied from the ionic assets folder. 

openDatabase doesn't exists on SQLite one import as...
 import { SQLite, SQLiteObject, SQLiteDatabaseConfig } from '@ionic-native/sqlite/ngx';

**Comment by brody2consult** [comment]
minimal, reproducible example (<https://stackoverflow.com/help/minimal-reproducible-example>) is needed

**Comment by brody2consult** [comment]
with apologies for the delay
