### ISSUE TITLE
Testing prettier with Typescript 4.1 beta

### ISSUE THREAD

**Issue by sandersn** [brodybits/ask-me-anything#31]
Are you still contributing to prettier? Prettier is JS code type-checked with Typescript, and I changed the way CommonJS imports work in 4.1. It turns out the prettier is the only code I could find that used nested destructuring with a require call:

```js
const { utils: { nub, intercalate } } = require('./monopackage')
```

I restored the old behaviour for this pattern in https://github.com/microsoft/TypeScript/pull/40188 &mdash; it's a lot of work to support it correctly &mdash; but I'd like somebody on the prettier project to test it and make sure it works the same as it used to. Is that something you could do or can you point me to a good person?

**Comment by brody2consult** [comment]
I guess we will continue discussion in <https://github.com/microsoft/TypeScript/issues/40578>.

Thanks Nathan for your efforts to support Prettier. I contribute whenever I can, which is generally not as much as I would like. Please feel free to ask again, any time.
